name: OIDC Continuous Deployment

# This workflow is triggered whenever commits are pushed to the main branch and from the web folder
on:
  push:
    branches:
      - 'main'
    paths:
      - 'web/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    # Define the working directory for all run steps in the workflow
    working-directory: ./web

jobs:

  deploy_production:
    environment: production
    name: 'Deploy to production'
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::506857912201:role/OIDC_actions_EB_deployment
        role-session-name: ElasticBeanstalkDeployment
        aws-region: eu-west-2

    - name: Sts GetCallerIdentity
      run: aws sts get-caller-identity

    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install GCC
      run: brew install gcc

    - name: Deploy changes
      run: |
        brew install awsebcli
        eb deploy